import { AUTH_DOMAIN, API_KEY, PROJECTID, STORAGE_BUCKET, MESSAGING_SENDER_ID, APP_ID, MEASUREMENT_ID } from "@env";


export default {
    API_KEY,
    AUTH_DOMAIN,
    PROJECTID,
    STORAGE_BUCKET,
    MESSAGING_SENDER_ID,
    APP_ID,
    MEASUREMENT_ID
}